# Covering the basics of tensorflow and and funamental concepts of tensors

This notebook will cover:
* Into to tensors
* getting info from tensors
* manipulating tensors
* tensors & numpy
* using @tf.function
* use GPUS with TF
* additional practice of the above 

# intro to tensors

In [1]:
# import tensorflow
import tensorflow as tf
print(tf.__version__)

2.3.1


### create tensors with tf.constant()

In [2]:
scalar = tf.constant(7)
print(scalar)
# check dimentions of scalar
print(scalar.ndim)

tf.Tensor(7, shape=(), dtype=int32)
0


In [3]:
# Create a vencor
vector = tf.constant([10, 10])
print(vector)
# check dimentions of vector
print(vector.ndim)

tf.Tensor([10 10], shape=(2,), dtype=int32)
1


In [4]:
# Create a matrix, more then one dim
matrix = tf.constant([[10, 10],
                     [7,7]])
print(matrix)
# check dimentions of matrix
print(matrix.ndim)

tf.Tensor(
[[10 10]
 [ 7  7]], shape=(2, 2), dtype=int32)
2


In [5]:
# Create another matrix
another_matrix = tf.constant([[10., 10.],
                             [7.,7.],
                             [4.,4.]], dtype=tf.float16) #specify datatype
print(another_matrix)
# check dimentions of another_matrix
print(another_matrix.ndim)

tf.Tensor(
[[10. 10.]
 [ 7.  7.]
 [ 4.  4.]], shape=(3, 2), dtype=float16)
2


In [6]:
# create a tensor 
tensor = tf.constant([
    [
        [10,10,10],[7,7,7]
    ],
    [
        [1,1,1],[3,3,3]
    ],
    [
        [2,2,2],[5,5,5]
    ],
])
print(tensor)
# check dimentions of tensor
print(tensor.ndim)

tf.Tensor(
[[[10 10 10]
  [ 7  7  7]]

 [[ 1  1  1]
  [ 3  3  3]]

 [[ 2  2  2]
  [ 5  5  5]]], shape=(3, 2, 3), dtype=int32)
3


### create tensors with tf.variable()

In [7]:
#create the same tensor as above 
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [8]:
# try .assign() to modify tensor
print(changeable_tensor[0], changeable_tensor)
changeable_tensor[0].assign(7)
print(changeable_tensor[0], changeable_tensor)

tf.Tensor(10, shape=(), dtype=int32) <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>
tf.Tensor(7, shape=(), dtype=int32) <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>


In [9]:
# the above can't be done with tf.constant()
# unchangeable_tensor[0].assign(7)

### creating random tensor

these are tensors of arbitary size containg random numbers

In [10]:
# create two random tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2)) # creates tensor based on normal distribution
print(random_1)

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.uniform(shape=(3,2)) # creates tensor based on uniform distribution
print(random_2)

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[0.7493447  0.73561966]
 [0.45230794 0.49039817]
 [0.1889317  0.52027524]], shape=(3, 2), dtype=float32)


### suffle order of tensor elements

In [11]:
not_suffled = tf.constant([[10,7],
                           [3,4],
                           [2,5]])
print(not_suffled)
print(tf.random.shuffle(not_suffled, seed=42)) #suffles along first dim
print(tf.random.shuffle(not_suffled, seed=42)) #diff everytime
print(tf.random.shuffle(not_suffled, seed=42))
#seed=42 here sets operation level seed 

tf.Tensor(
[[10  7]
 [ 3  4]
 [ 2  5]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  5]
 [ 3  4]
 [10  7]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  5]
 [ 3  4]
 [10  7]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[10  7]
 [ 3  4]
 [ 2  5]], shape=(3, 2), dtype=int32)


In [12]:
tf.random.set_seed(42) # here sets global level seed
print(tf.random.shuffle(not_suffled, seed=42))
print(tf.random.shuffle(not_suffled, seed=42))
print(tf.random.shuffle(not_suffled, seed=42)) 
print(tf.random.shuffle(not_suffled, seed=42))
print(tf.random.shuffle(not_suffled, seed=42))

#

tf.Tensor(
[[10  7]
 [ 3  4]
 [ 2  5]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  5]
 [10  7]
 [ 3  4]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  5]
 [10  7]
 [ 3  4]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 3  4]
 [ 2  5]
 [10  7]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 3  4]
 [ 2  5]
 [10  7]], shape=(3, 2), dtype=int32)
