# Covering the basics of tensorflow and and funamental concepts of tensors

This notebook will cover:
* Into to tensors
* getting info from tensors
* manipulating tensors
* tensors & numpy
* using @tf.function
* use GPUS with TF
* additional practice of the above 

# intro to tensors

In [1]:
# import tensorflow
import tensorflow as tf
print(tf.__version__)

2.3.1


### create tensors with tf.constant()

In [2]:
scalar = tf.constant(7)
print(scalar)
# check dimentions of scalar
print(scalar.ndim)

tf.Tensor(7, shape=(), dtype=int32)
0


In [3]:
# Create a vencor
vector = tf.constant([10, 10])
print(vector)
# check dimentions of vector
print(vector.ndim)

tf.Tensor([10 10], shape=(2,), dtype=int32)
1


In [4]:
# Create a matrix, more then one dim
matrix = tf.constant([[10, 10],
                     [7,7]])
print(matrix)
# check dimentions of matrix
print(matrix.ndim)

tf.Tensor(
[[10 10]
 [ 7  7]], shape=(2, 2), dtype=int32)
2


In [5]:
# Create another matrix
another_matrix = tf.constant([[10., 10.],
                             [7.,7.],
                             [4.,4.]], dtype=tf.float16) #specify datatype
print(another_matrix)
# check dimentions of another_matrix
print(another_matrix.ndim)

tf.Tensor(
[[10. 10.]
 [ 7.  7.]
 [ 4.  4.]], shape=(3, 2), dtype=float16)
2


In [6]:
# create a tensor 
tensor = tf.constant([
    [
        [10,10,10],[7,7,7]
    ],
    [
        [1,1,1],[3,3,3]
    ],
    [
        [2,2,2],[5,5,5]
    ],
])
print(tensor)
# check dimentions of tensor
print(tensor.ndim)

tf.Tensor(
[[[10 10 10]
  [ 7  7  7]]

 [[ 1  1  1]
  [ 3  3  3]]

 [[ 2  2  2]
  [ 5  5  5]]], shape=(3, 2, 3), dtype=int32)
3


### create tensors with tf.variable()

In [7]:
#create the same tensor as above 
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [8]:
# try .assign() to modify tensor
print(changeable_tensor[0], changeable_tensor)
changeable_tensor[0].assign(7)
print(changeable_tensor[0], changeable_tensor)

tf.Tensor(10, shape=(), dtype=int32) <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>
tf.Tensor(7, shape=(), dtype=int32) <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>


In [9]:
# the above can't be done with tf.constant()
# unchangeable_tensor[0].assign(7)

### creating random tensor

these are tensors of arbitary size containg random numbers

In [10]:
# create two random tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2)) # creates tensor based on normal distribution
print(random_1)

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.uniform(shape=(3,2)) # creates tensor based on uniform distribution
print(random_2)

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[0.7493447  0.73561966]
 [0.45230794 0.49039817]
 [0.1889317  0.52027524]], shape=(3, 2), dtype=float32)


### suffle order of tensor elements

In [11]:
not_suffled = tf.constant([[10,7],
                           [3,4],
                           [2,5]])
print(not_suffled)
print(tf.random.shuffle(not_suffled, seed=42)) #suffles along first dim
print(tf.random.shuffle(not_suffled, seed=42)) #diff everytime
print(tf.random.shuffle(not_suffled, seed=42))
#seed=42 here sets operation level seed 

tf.Tensor(
[[10  7]
 [ 3  4]
 [ 2  5]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  5]
 [ 3  4]
 [10  7]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  5]
 [ 3  4]
 [10  7]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[10  7]
 [ 3  4]
 [ 2  5]], shape=(3, 2), dtype=int32)


In [12]:
tf.random.set_seed(42) # here sets global level seed
print(tf.random.shuffle(not_suffled, seed=42))
print(tf.random.shuffle(not_suffled, seed=42))
print(tf.random.shuffle(not_suffled, seed=42)) 
print(tf.random.shuffle(not_suffled, seed=42))
print(tf.random.shuffle(not_suffled, seed=42))

# both operation and global seeds are used to generate a random sequence

tf.Tensor(
[[10  7]
 [ 3  4]
 [ 2  5]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  5]
 [10  7]
 [ 3  4]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  5]
 [10  7]
 [ 3  4]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 3  4]
 [ 2  5]
 [10  7]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 3  4]
 [ 2  5]
 [10  7]], shape=(3, 2), dtype=int32)


### other ways to make tensors

In [1]:
import numpy as np

In [3]:
# create a tensor of all 1s
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [5]:
# create a tensor of all 0s
tf.zeros(shape=(10, 7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### turn numpy arrays into tensors

main differnece between numpy arrays and tf tensors is that tensors run faster on a GPU

In [13]:
#make numpy array
numpy_a = np.arange(1, 25, dtype=np.int32)
#set array to tensor
A = tf.constant(numpy_a, shape=(2, 3, 4))
print(A)
B = tf.constant(numpy_a)
print(B)

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)
tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,), dtype=int32)


### getting info from tensors

* shape
* rank
* axis/dimension
* size

In [16]:
#shape 
A.shape

TensorShape([2, 3, 4])

In [18]:
#
A.ndim

3

In [23]:
# axis/dimension
print(A[0]) # pulls first dimenstion
print(A[:, 1]) #pulls first axis in all dimenbtions

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[ 5  6  7  8]
 [17 18 19 20]], shape=(2, 4), dtype=int32)


In [26]:
tf.size(A)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [2]:
#create rank 4 tensor 
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [3]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [4]:
tf.size(rank_4_tensor).numpy()

120

### indexing tensor 

In [9]:
# get first two elements of each dimention 
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [11]:
# get the first element from each dimention minus the final one
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [14]:
# create a rank 2 tensor
rank_2_tensor = tf.constant([[10, 7],[3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim, tf.size(rank_2_tensor)

(TensorShape([2, 2]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [15]:
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [16]:
# add extra dim to rank 2 tensor 
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [18]:
#alternitive for above
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [19]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]])>

### manipulating tensors (tensor operations)

**basic operations**
`+` `-` `*` `/`

In [25]:
tensor = tf.constant([[10, 7],[3,4]])
tensor + 10, tensor + [10, 1], tensor
# tensor does not change unless we set it to itsself

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20,  8],
        [13,  5]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>)

In [26]:
tensor * 10, tensor * [10, 1], 

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,   7],
        [ 30,   4]])>)

In [27]:
tensor - 10, tensor - [10, 1], 

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-7, -6]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0,  6],
        [-7,  3]])>)

In [35]:
# tensor flow funtions can be use as well
tf.multiply(tensor, 10) # using tf is faster on a gpu then tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

**matrix multiplication**

matrix multiplication is the most common operators

rules for tensors
1. Inner dimentions must match
2. Resulting matrix has the shape of inner dimentions

In [31]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [32]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]])>

In [34]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [43]:
x = tf.constant([[1, 2],[3,4], [5, 6]])

y = tf.constant([[7, 8],[9,10], [11, 12]])
x , x.shape, y, y.shape

# tf.matmul(x, y) can't be done since x and y inner dimentions don't match

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 TensorShape([3, 2]),
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>,
 TensorShape([3, 2]))

In [44]:
# to multiply these matrix's we can reshape one or both
#change shape of y
tf.reshape(y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [55]:
# now we can multiply them
tf.matmul(x, tf.reshape(y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [52]:
x.shape, tf.reshape(y, shape=(2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [53]:
tf.matmul(tf.reshape(x, shape=(2,3)), y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

In [54]:
tf.reshape(x, shape=(2,3)).shape, y.shape
# resulting matrixes are the size of the outer dimentions

(TensorShape([2, 3]), TensorShape([3, 2]))

In [57]:
# can do the same with transpose 
x, tf.transpose(x), tf.reshape(x, shape=(2,3))

# transpose flips the dimentions while reshape with shuffle the matrix to fit the shape

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>)

In [58]:
tf.matmul(tf.transpose(x), y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [66]:
tf.matmul(tf.transpose(y), x)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89, 116],
       [ 98, 128]])>

**dot products**

matrix multiplcation is also know as dot product. 

you can preform this using
* `tf.matmul`
* `tf.tesnordot`

In [67]:
# preform the dot product on x and y
tf.tensordot(x, tf.transpose(y), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [68]:
tf.tensordot(tf.transpose(x), y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [70]:
y, tf.transpose(y), tf.reshape(y, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]])>)

### changing data types